### create project
Post http://localhost:3000/project/create
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "title" : "IDK the number",
    "text" : "this is a test this is a test"
    
}

### getting the list of projects
Get http://localhost:3000/project/list
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

### getting project by ID
Get http://localhost:3000/project/631896d1de820178e0142bf0
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json