### create project
Post http://localhost:3000/project/create
Authorization: {{$dotenv token}}
Content-Type: application/json

{
    "title" : "the first project",
    "text" : "please work.... I need to get this done man!"
    
}