### create teams
Post http://localhost:3000/team/create
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "name" : "team 2",
    "description" : "this is a caption for the first team",
    "username" : "zizion"
}

### getting the list of teams
Get http://localhost:3000/team/list
Authorization: Beare {{$dotenv token}}
Content-Type: application/json

### getting a team by ID
Get http://localhost:3000/team/631d7d78c4d9c90eb5f1496d
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

### getting my teams
Get http://localhost:3000/team/me
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

### deleting a team by ID
Delete http://localhost:3000/team/remove/631d7d78c4d9c90eb5f1496d
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json
