### Get User Profile
Get http://localhost:3000/user/profile
Authorization: Bearer {{$dotenv token}}

### Edit Profile
Post http://localhost:3000/user/profile
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

{
    "first_name": "",
    "last_name": "",
    "skills": ["nodejs", "expressjs", "photography"]
}

### getting all user's requests
Get http://localhost:3000/user/requests
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json

### getting user's requests by status
Get http://localhost:3000/user/requests/pending
Authorization: Bearer {{$dotenv token}}
Content-Type: application/json
